# ________________________________________________
#
#       CHAMPION TICKETS LANGUAGE FILE
#
# Here you can customise Bot's Messages.
#
# ________________________________________________

general:
  no_user: "You haven't mentioned user to add to the ticket."
  # Valid Placeholders: <role>
  no_role: "You need <role> Role to use this command."
  not_set: "You don't have that option set so it cannot be reseted." 
  cmd_disabled: "This command is disabled on this server."
  no_perm: "You don't have permission to perform this command." 
  msgid: "You have entered Invalid Message ID"
  usage: "Invalid Usage for Command. Usage: `<usage>`"
  ping_loading: "Ping.."
  ping: "Bot Uptime is <uptime>, bot ping <bot>ms, api ping <api>ms"
  auto_response: "Hey <user>, <response>."
  auto_announce: "<message>."
  cooldown: "You're on cooldown on that command for <cooldown>"
  invalid_cmd: "You have provided Invalid Command"
  no_commands: "No Commands in this Category"
  suggestions:
    accepted: "Suggestion have been accepted successfully"
    denied: "Suggestion have been denied successfully"
    deleted: "Suggestion have been deleted successfully"
    sent: "Your Suggestion have been successfully sent."
    vote_yes: "You have UpVoted this Suggestion."
    vote_no: "You have DownVoted this Suggestion."
    vote_reset: "Your Vote have been reseted."
    placeholder: "Select decision option for this Suggestion"
    decision:
      accept: "Accept Suggestion"
      deny: "Deny Suggestion"
      delete: "Delete Suggestion"
    not_voted: "You cannot reset Vote because you didn't vote."
    already_voted: "You have already voted, please reset your Vote"
buttons:
  confirm_close: "Yes, I'm sure"
  cancel_close: "No, don't close it yet"
  create: "Create Ticket"
  close: "Close Ticket"
  go_ticket: "Go to Ticket"
  next: "Next"
  previous: "Previous"
  download: "Download"
  link: "Get Link"
  yes_vote: "Yes"
  no_vote: "No"
  remove_vote: "Remove Vote"
titles:
  help: "🚀 · Help Menu"
  error: "Error"
  auto_response: "Auto Response"
  auto_announce: "Auto Announce"
  closed_dm: "Thank you for contacting us"
  answers: "Answers"
  questions: "Questions"
  products: "List of Products Available"
  sugg_accepted: "Suggestion accepted"
  sugg_denied: "Suggestion denied"
ticket:
  already_open: "Sorry, you already have an ticket opened, close it before opening another."
  have_in_sel: "You already have an ticket waiting for Category Selection, close it or select category."
  no_category: "Category for tickets isn't setuped yet, ticket couldn't be opened."
  no_panel: "Panel Channel isn't setuped yet, ticket couldn't be opened."
  no_transcript: "Channel for Transcripts isn't setuped yet, ticket couldn't be opened."
  no_transcript_msg: "Transcript Message isn't setuped yet, ticket couldn't be opened."
  no_suggest: "Suggestions Channel isn't setuped yet, ticket couldn't be opened."
  user_added: "You have successfully added <user> to the ticket."
  user_removed: "You have successfully removed <user> from the ticket."
  ticket_channel: "This command can only be used in Tickets Channel."
  close_confirmation: "Are you sure you want to close ticket? Click on Button to Confirm your decision."
  bl_role: "You cannot open Ticket because you have role which is Blacklisted from opening them."
  bl_user: "You cannot open Ticket because you are Blacklisted from opening them."
  ticket_created: "Hey <user>, your Ticket have been created in channel <channel>."
  time_expired: "Time for decision has passed without answer, ticket won't be deleted."
  ticket_deleted: "Ticket will be deleted in few seconds.."
  cancel_delete: "You have successfully canceled ticket deletation."
  channel_topic: "Ticket opened by <author>."
  have_ticket_category: "You already have maximum number of opened tickets in that category."
  already_claimed: "This Ticket is already claimed"
  ticket_claimed: "Ticket have been claimed by <user>"
  ticket_assigned: "Ticket have been assigned to <user> by <author>."
  invalid_category: "You have provided Invalid Category Name/ID"
  category_moved: "Ticket have been moved to <category> Category by <user>"
  not_separate: "Config Fields 'separateCategories' & 'category > status' need to be enabled in order to use this Command."
  move_topic: "Ticket have been moved to <category> by <user>"
  closed_dm: "Hey, thank you for contacting us. We will be grateful if you review your seller using `-review` Command."
  loading_answers: "Loading Answers, please wait."
  question_idle: "Time to answer questions have expired, you can no longer answer"
  panel_created: "Ticket Panel have been created successfully."
  priority:
    changed: "Priority of Ticket Channel <channel> have been changed to <priority>."
    invalid: "You have entered invalid priority. Valid: Low, Normal, High, Urgent."
    list: "**Urgent Priority**:\n<urgent>\n\n**High Priority**:\n<high>"
    no_high: "> No High Priority Tickets"
    no_urgent: "> No Urgent Priority Tickets"
  invalid_panel: "Ticket couldn't be created because such Ticket Category doesn't exist."
utility:
  getid: "ID of <type> is `<id>`."
  no_text: "You haven't provided text for suggestion"
  counters_started: "Counters have started creating, please wait."
  counters_created: "Counters have been created."
  claimed_counter: "Claimed Tickets: <stats>"
  total_counter: "Total Tickets: <stats>"
  opened_counter: "Open Tickets: <stats>"
  counters_category: "Tickets Statistics"
  math_error: "An Error occurred during calculation."
service:
  invalid_user: "You haven't mentioned user."
  invalid_mail: "You have entered invalid Email."
  invalid_price: "You have entered invalid amount to be payed."
  invalid_service: "You have entered invalid Service which need to be payed."
  invalid_rating: "You have entered invalid Rating (1-5)."
  invalid_comment: "You have entered invalid Review Comment."
  no_review: "Review with that ID cannot be found."
  review_self: "You cannot Review yourself"
  status: "Your Freelancer Status have been changed to __<status>__."
  availability:
    available: "Available"
    unavailable: "Unavailable"
  no_paypal: "No PayPal Set"
  no_hours: "No Available Hours"
  note_added: "Channel Note have been changed to `<note>`."
  note_reseted: "Channel Note have been reseted."
  hours_added: "Available Hours have been changed to `<hours>`."
  hours_reseted: "Available Hours have been reseted."
  paypal_added: "Your PayPal have been changed to `<paypal>`."
  paypal_reseted: "Your PayPal have been reseted."
  bio_added: "Your Bio have been changed to `<bio>`." 
  bio_reseted: "Your Bio have been reseted."
  invalid_crypto: "You have entered Invalid Crypto Currency"
  reviews:
    comment: "Hey, we noticed your ticket has been recently closed on our Server.\nWe would like to know how much you're satisfied with our Support by Leaving your Review Below.\nTo cancel just type 'cancel'"
    star: "Please use Buttons to rate our Support from 1 - 5 ⭐"
    sent: "Thank you for your response! Review have been sent successfully."
    time: "Time for providing comment/rating has passed without answer."
    cannot_review: "You cannot review that User"
    cancel: "Review Process have been canceled"
products:
  # Available Placeholders: <file> (Name of File)
  download_get: "Click on Button below to get download for your file (<file>)"
  # Available Placeholders: <link> (Name of Link)
  link_get: "Click on Button below to get your link (<link>)"
  # Available Placeholders: <file> (Name of File)
  download: "Click on Button below to download your file (<file>)"
  # Available Placeholders: <link> (Name of Link)
  link: "Click on Button below to go to your link (<link>)"
  # Available Placeholders: <role> (List of Required Roles)
  roles: "You need <role> Role(s) to be able do get this product"
  permissions: "You don't have permission to get this product"
  invalid_product: "Product with such ID doesn't exist"
  none_type: "This Product cannot be downloaded."
sellix:
  no_id: "Order with such ID couldn't be found"
  used_id: "Someone has already been verified with that Order ID"
  # Available Placeholders: <product> (Product Purchased), <roles> (Roles Obtained)
  verified: "You have successfully connected your Discord with Purchase of <product> on Sellix"
  no_product: "Product couldn't be found."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
tebex:
  no_id: "Transaction with such ID couldn't be found"
  used_id: "Someone has already been verified with that Transaction ID"
  # Available Placeholders: <packages> (Packages Purchased), <roles> (Roles Obtained)
  verified: "You have successully connected your Discord with Purchase of <packages> Package(s) on Tebex."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
cstore:
  no_id: "Transaction with such ID couldn't be found"
  used_id: "Someone has already been verified with that Transaction ID"
  # Available Placeholders: <packages> (Packages Purchased), <roles> (Roles Obtained)
  verified: "You have successully connected your Discord with Purchase of <packages> Package(s) on CraftingStore."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
  no_package: "No Package Found."
